extends:
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

rules:
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/no-this-alias': off
  import/no-unresolved: off
  no-console: ['warn', { allow: ['error', 'warn', 'info', 'debug'] }]
  prettier/prettier: warn
