name: Tests

on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]

env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
          node-version: ${{ matrix.node-version }}

      - run: vp install --frozen-lockfile
      - run: vp run test:export

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test/testResults.xml

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - run: vp install --frozen-lockfile
      - run: vp run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - run: vp install --frozen-lockfile
      - run: vp run build
